language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

addons:
  apt:
    packages:
    - shellcheck

script:
 - shellcheck -e SC2016 afzcamcreator.sh

matrix:
  fast_finish: true
